export default [
    {
        "id": 1,
        "time": "2023-08-01T12:00:00Z",
        "foodName": "Bread Loaf",
        "foodCategory": "Bakery",
        "quantity": 10,
        "producedAt": "2023-07-31T18:00:00Z",
        "consumedBy": "2023-07-31T22:00:00Z",
        "foodTags": ["Vegan", "Whole Grain"],
        "allergens": ["Wheat"],
        "collectionAddress": "123 Main St, Anytown USA",
        "beneficiary": "John Doe",
        "beneficiaryContact": "555-1234",
        "donor": "Local Bakery",
        "donorContact": "555-5678",
        "status": "Collected",
        "operatingHours": "9 AM - 5 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Loaves are fresh and ready for donation."
    },
    {
        "id": 2,
        "time": "2023-08-02T10:30:00Z",
        "foodName": "Apples",
        "foodCategory": "Produce",
        "quantity": 50,
        "producedAt": "2023-08-01T15:00:00Z",
        "consumedBy": "2023-08-01T19:00:00Z",
        "foodTags": ["Organic"],
        "allergens": [],
        "collectionAddress": "456 Oak St, Anytown USA",
        "beneficiary": "John Doe",
        "beneficiaryContact": "555-9012",
        "donor": "Local Bakery",
        "donorContact": "555-3456",
        "status": "Collected",
        "operatingHours": "10 AM - 6 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Apples are fresh and in good condition."
    },
    {
        "id": 3,
        "time": "2023-08-03T14:15:00Z",
        "foodName": "Chicken Breasts",
        "foodCategory": "Meat",
        "quantity": 20,
        "producedAt": "2023-08-02T09:00:00Z",
        "consumedBy": "2023-08-02T13:00:00Z",
        "foodTags": ["Hormone-free"],
        "allergens": ["Poultry"],
        "collectionAddress": "789 Elm St, Anytown USA",
        "beneficiary": "John Doe",
        "beneficiaryContact": "555-7890",
        "donor": "Local Bakery",
        "donorContact": "555-2345",
        "status": "Collected",
        "operatingHours": "11 AM - 7 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Chicken is fresh and ready for cooking."
    },
    {
        "id": 4,
        "time": "2023-08-04T09:45:00Z",
        "foodName": "Spicy Curry",
        "foodCategory": "Prepared Meal",
        "quantity": 15,
        "producedAt": "2023-08-03T16:00:00Z",
        "consumedBy": "2023-08-03T20:00:00Z",
        "foodTags": ["Spicy", "Halal"],
        "allergens": ["Dairy", "Wheat"],
        "collectionAddress": "321 Oak Rd, Anytown USA",
        "beneficiary": "Anytown Community Center",
        "beneficiaryContact": "555-4321",
        "donor": "Local Indian Restaurant",
        "donorContact": "555-8765",
        "status": "Collected",
        "operatingHours": "8 AM - 8 PM",
        "handleFood": "Delivery",
        "additionalNotes": "Curry is freshly made and ready to serve."
    },
    {
        "id": 5,
        "time": "2023-08-05T11:00:00Z",
        "foodName": "Veggie Stir-fry",
        "foodCategory": "Prepared Meal",
        "quantity": 20,
        "producedAt": "2023-08-04T14:30:00Z",
        "consumedBy": "2023-08-04T17:30:00Z",
        "foodTags": ["Vegan", "Gluten-free"],
        "allergens": ["Soy"],
        "collectionAddress": "654 Maple St, Anytown USA",
        "beneficiary": "Anytown Shelter",
        "beneficiaryContact": "555-6789",
        "donor": "Local Vegan Restaurant",
        "donorContact": "555-2109",
        "status": "Collected",
        "operatingHours": "9 AM - 7 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Stir-fry is fresh and ready to be served."
    },
    {
        "id": 6,
        "time": "2023-08-06T13:30:00Z",
        "foodName": "Halal Meat Platter",
        "foodCategory": "Meat",
        "quantity": 25,
        "producedAt": "2023-08-05T11:00:00Z",
        "consumedBy": "2023-08-05T15:00:00Z",
        "foodTags": ["Halal"],
        "allergens": ["Meat"],
        "collectionAddress": "987 Elm Rd, Anytown USA",
        "beneficiary": "Anytown Mosque",
        "beneficiaryContact": "555-3210",
        "donor": "Local Halal Butcher",
        "donorContact": "555-6543",
        "status": "Collected",
        "operatingHours": "12 PM - 8 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Meat is freshly prepared and ready for distribution."
    },
    {
        "id": 7,
        "time": "2023-08-07T16:00:00Z",
        "foodName": "Vegan Chili",
        "foodCategory": "Prepared Meal",
        "quantity": 18,
        "producedAt": "2023-08-06T14:00:00Z",
        "consumedBy": "2023-08-06T19:00:00Z",
        "foodTags": ["Vegan", "Gluten-free"],
        "allergens": ["Soy"],
        "collectionAddress": "159 Oak St, Anytown USA",
        "beneficiary": "Anytown Food Pantry",
        "beneficiaryContact": "555-8901",
        "donor": "Local Bakery",
        "donorContact": "555-4567",
        "status": "Collected",
        "operatingHours": "10 AM - 6 PM",
        "handleFood": "Delivery",
        "additionalNotes": "Chili is freshly made and ready to serve."
    },
    {
        "id": 8,
        "time": "2023-08-08T15:30:00Z",
        "foodName": "Spicy Chicken Tacos",
        "foodCategory": "Prepared Meal",
        "quantity": 22,
        "producedAt": "2023-08-07T13:00:00Z",
        "consumedBy": "2023-08-07T13:00:00Z",
        "foodTags": ["Spicy", "Halal"],
        "allergens": ["Poultry", "Wheat"],
        "collectionAddress": "321 Oak Rd, Anytown USA",
        "beneficiary": "Anytown Community Center",
        "beneficiaryContact": "555-4321",
        "donor": "Local Mexican Restaurant",
        "donorContact": "555-8765",
        "status": "Collected",
        "operatingHours": "8 AM - 8 PM",
        "handleFood": "Delivery",
        "additionalNotes": "Tacos are freshly made and ready to serve."
    },
    {
        "id": 9,
        "time": "2023-08-09T11:15:00Z",
        "foodName": "Vegan Sushi Rolls",
        "foodCategory": "Prepared Meal",
        "quantity": 16,
        "producedAt": "2023-08-08T16:30:00Z",
        "consumedBy": "2023-08-08T16:30:00Z",
        "foodTags": ["Vegan", "Gluten-free"],
        "allergens": ["Soy"],
        "collectionAddress": "654 Maple St, Anytown USA",
        "beneficiary": "Anytown Shelter",
        "beneficiaryContact": "555-6789",
        "donor": "Local Bakery",
        "donorContact": "555-2109",
        "status": "Collected",
        "operatingHours": "9 AM - 7 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Sushi rolls are fresh and ready to be served."
    },
    {
        "id": 10,
        "time": "2023-08-10T12:45:00Z",
        "foodName": "Halal Lamb Kebabs",
        "foodCategory": "Meat",
        "quantity": 30,
        "producedAt": "2023-08-09T10:00:00Z",
        "consumedBy": "2023-08-09T10:00:00Z",
        "foodTags": ["Halal", "Spicy"],
        "allergens": ["Meat"],
        "collectionAddress": "987 Elm Rd, Anytown USA",
        "beneficiary": "Anytown Mosque",
        "beneficiaryContact": "555-3210",
        "donor": "Local Halal Catering",
        "donorContact": "555-6543",
        "status": "Collected",
        "operatingHours": "12 PM - 8 PM",
        "handleFood": "Pickup",
        "additionalNotes": "Kebabs are freshly prepared and ready for distribution."
    }
]